<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <StartupObject>IndusBrawl.Laser.Server.Program</StartupObject>
    <Configurations>Debug;Release;SHIT</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AStarPathFinder" Version="1.0.0" />
    <PackageReference Include="Colorful.Console" Version="1.2.15" />
    <PackageReference Include="MySql.Data" Version="8.0.29" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IndusBrawl.Laser.Logic\IndusBrawl.Laser.Logic.csproj" />
    <ProjectReference Include="..\IndusBrawl.Laser.Titan\IndusBrawl.Laser.Titan.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="fridascript.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="wwwroot\**;PatchAssets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="admin_www\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="starrdrop_lab.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="starrdrop_loot.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="gameplay.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
